import {criteria} from './domain.ts';
export const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const date=(v:unknown)=>new Date(String(v)).toLocaleString('en-US',{timeZone:'America/Denver',dateStyle:'medium',timeStyle:'short'});
export function layout(title:string,body:string,csrf='',notice='') {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · PartnerOS</title><link rel="stylesheet" href="/style.css"></head><body><aside><a class="brand" href="/">◈ PartnerOS</a><span class="eyebrow">RUNPOD / PARTNER DEVELOPMENT</span><nav><a href="/">Overview & pipeline</a><a href="/?stage=review">Review queue</a><a href="/settings">Settings & integrations</a></nav><div class="sidefoot">Phase 1 · Research & review<br>External actions disabled${csrf?`<form method="post" action="/logout">${token(csrf)}<button class="quiet">Sign out</button></form>`:''}</div></aside><main>${notice?`<div class="notice" role="status">${esc(notice)}</div>`:''}${body}<footer>Runpod · Advisory research. Partner interest must be confirmed in conversation.</footer></main></body></html>`;}
export const token=(csrf:string)=>`<input type="hidden" name="csrf" value="${esc(csrf)}">`;
export const badge=(stage:string)=>`<span class="badge ${esc(stage)}">${esc(stage.replaceAll('_',' '))}</span>`;
export function login(){return layout('Sign in',`<section class="login card"><span class="eyebrow">PRIVATE WORKSPACE</span><h1>Partner development,<br>with a human in charge.</h1><p>Sign in to review research and decide what happens next.</p><form method="post" action="/login"><label>Reviewer password<input type="password" name="password" required autocomplete="current-password" maxlength="256"></label><button>Sign in</button></form></section>`);}
export function overview(rows:any[],csrf:string,paused:boolean,stage:string,query:string,notice:string){const filtered=rows.filter(c=>(!stage||c.stage===stage)&&(!query||`${c.name} ${c.domain} ${c.segment}`.toLowerCase().includes(query.toLowerCase())));return layout('Pipeline',`
<header><span class="eyebrow">PARTNER DEVELOPMENT</span><h1>Build the right relationships.</h1><p>Research with evidence. Review with context. Keep the next step clear.</p></header>
${paused?'<div class="notice">Research is paused. Queued work will wait.</div>':''}
<div class="metrics">${[['Candidates',rows.length],['Ready for review',rows.filter(c=>c.stage==='review').length],['Research accepted',rows.filter(c=>c.stage==='accepted').length],['Needs attention',rows.filter(c=>c.stage==='blocked').length]].map(([k,v])=>`<div class="card"><strong>${v}</strong><span>${k}</span></div>`).join('')}</div>
<section class="card"><div class="sectionhead"><h2>Candidate pipeline</h2><span>${filtered.length} candidates</span></div><form class="filters" method="get"><input aria-label="Search candidates" name="q" placeholder="Search company, website or segment" value="${esc(query)}"><select name="stage" aria-label="Stage"><option value="">All stages</option>${['new','researching','review','accepted','rejected','nurture','blocked'].map(s=>`<option ${s===stage?'selected':''}>${s}</option>`).join('')}</select><button class="secondary">Filter</button></form>
<div class="tablewrap"><table><thead><tr><th>Company</th><th>Segment</th><th>Stage</th><th>Relationship</th><th>Updated · Denver</th></tr></thead><tbody>${filtered.map(c=>`<tr><td><a href="/candidates/${c.id}">${esc(c.name)}</a><small>${esc(c.domain)}</small></td><td>${esc(c.segment)}</td><td>${badge(c.stage)}${c.suppressed?' <span class="badge blocked">Suppressed</span>':''}</td><td>${c.existing_relationship?'Existing relationship':'Not checked externally'}</td><td>${date(c.updated_at)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No candidates yet. Add a company below to start a research brief.</td></tr>'}</tbody></table></div></section>
<section class="card"><h2>Add a company to research</h2><p>Start with a specific company. Broad sourcing and CRM matching come in later releases.</p><form action="/candidates" method="post">${token(csrf)}<div class="grid"><label>Company name<input name="name" required maxlength="160" placeholder="Company name"></label><label>Company website<input name="website" required maxlength="500" placeholder="https://company.com"></label><label>Partner segment<input name="segment" required maxlength="100" placeholder="Inference tools, distribution, infrastructure…"></label></div><label>Research brief<textarea name="brief" required minlength="10" maxlength="4000" placeholder="What joint use case should we investigate? Include desired outcomes and exclusions."></textarea></label><button>Add candidate</button></form></section>`,csrf,notice);}
function claim(c:any,evidence:any[]){return `<p>${esc(c.text)} ${c.evidence_ids.map((id:string)=>`<a class="source" href="#evidence-${esc(id)}">[${esc(id)}]</a>`).join('')}</p>`;}
export function detail(c:any,a:any,jobs:any[],reviews:any[],audit:any[],csrf:string,demo:boolean,notice:string){const r=a?.recommendation;return layout(c.name,`
<a class="back" href="/">← Candidate pipeline</a><header><span class="eyebrow">${esc(c.segment)}</span><h1>${esc(c.name)}</h1><p><a href="${esc(c.website)}" target="_blank" rel="noopener noreferrer">${esc(c.domain)} ↗</a> · ${badge(c.stage)} ${c.suppressed?badge('suppressed'):''}</p></header>
<div class="notice">Research recommendation only. Interest, opportunity, stakeholders and an accepted next step have not been conversation-validated. HubSpot and Notion matching are not connected.</div>
<section class="card"><div class="sectionhead"><h2>Research brief</h2><span>Colby · reviewer</span></div><p class="pre">${esc(c.brief)}</p>${!c.suppressed?`<form class="actions" method="post" action="/candidates/${c.id}/research">${token(csrf)}<button name="mode" value="live">Research approved sources</button>${demo?'<button class="secondary" name="mode" value="fixture">Run invented demo</button>':''}</form>`:'<p>Research disabled for this suppressed candidate.</p>'}</section>
${a?`<section class="card">${a.mode==='fixture'?'<div class="notice">DEMO / INVENTED DATA · This assessment is not research about this company.</div>':''}<div class="sectionhead"><h2>Latest recommendation</h2><span>${date(a.created_at)}</span></div><div class="metrics small"><div><strong>${a.score.fit??'Unknown'}</strong><span>Provisional fit / 100</span></div><div><strong>${a.score.coverage}%</strong><span>Evidence coverage</span></div><div><strong>${esc(r.confidence)}</strong><span>Model-assessed confidence</span></div></div><p class="muted">Hypothesis rubric v1. Fit is normalized over known dimensions only; it is not a probability or proof of partner quality.</p><h3>Summary</h3>${claim(r.summary,a.evidence)}<h3>Partnership thesis · hypothesis</h3>${claim(r.thesis,a.evidence)}<h3>Supporting claims · review required</h3>${r.claims.map((x:any)=>claim(x,a.evidence)).join('')}<table><thead><tr><th>Dimension</th><th>Rating</th><th>Reason</th></tr></thead><tbody>${r.dimensions.map((d:any,i:number)=>`<tr><td>${criteria[i]}</td><td>${d.rating===null?'Unknown':d.rating+' / 4'}</td><td>${claim({text:d.reason,evidence_ids:d.evidence_ids},a.evidence)}</td></tr>`).join('')}</tbody></table><h3>Unknowns</h3><ul>${r.unknowns.map((s:string)=>`<li>${esc(s)}</li>`).join('')}</ul><h3>Suggested next step</h3><p>${esc(r.next_action)}</p><details><summary>Unsent outreach draft</summary><p class="pre">${esc(r.outreach_draft)}</p><small>No sending capability is enabled.</small></details></section>
<section class="card"><h2>Source evidence</h2><p>Search-provider excerpts, not independently verified facts. Retrieval dates are not publication dates.</p>${a.evidence.map((e:any)=>`<article id="evidence-${esc(e.id)}"><h3>${esc(e.id)} · <a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a></h3><small>Retrieved ${date(e.retrieved_at)}</small><blockquote>${esc(e.excerpt)}</blockquote></article>`).join('')}</section>
<section class="card"><h2>Your review</h2><p>Accepting research does not approve outreach or qualify the partner.</p><form method="post" action="/candidates/${c.id}/review">${token(csrf)}<input type="hidden" name="version" value="${c.version}"><input type="hidden" name="assessment" value="${a.id}"><label>Decision notes<textarea name="comment" maxlength="4000" required></textarea></label><div class="actions"><button name="action" value="approve">Accept research</button><button class="secondary" name="action" value="more_research">Request more research</button><button class="secondary" name="action" value="nurture">Nurture</button><button class="danger" name="action" value="reject">Reject</button></div></form></section>`:'<section class="card empty"><h2>No assessment yet</h2><p>Queue research above. Missing credentials or failures will appear in run history.</p></section>'}
<section class="card"><h2>Human notes & relationship context</h2><form method="post" action="/candidates/${c.id}/notes">${token(csrf)}<input type="hidden" name="version" value="${c.version}"><label>Your notes<textarea name="notes" maxlength="8000">${esc(c.notes)}</textarea></label><label class="check"><input type="checkbox" name="relationship" ${c.existing_relationship?'checked':''}> Existing relationship known to you</label><button class="secondary">Save notes</button></form>${!c.suppressed?`<hr><form method="post" action="/candidates/${c.id}/suppress">${token(csrf)}<p>Suppressing stops research and marks this candidate as do not contact. Restoration requires an operator review.</p><button class="danger">Suppress candidate</button></form>`:''}</section>
<section class="card"><h2>Run history</h2>${jobs.map(j=>`<article><strong>${badge(j.state)} · ${esc(j.mode)}</strong><small>${date(j.created_at)} · Attempt ${j.attempts} · Reserved budget $${Number(j.budget_reserved).toFixed(3)}</small>${j.error?`<p class="error">${esc(j.error)}</p>`:''}${j.usage?`<p>Usage: ${esc(JSON.stringify(j.usage))}</p>`:''}</article>`).join('')||'<p>No runs yet.</p>'}<h3>Review history</h3>${reviews.map(x=>`<p>${date(x.created_at)} · ${esc(x.action)}: ${esc(x.comment)}</p>`).join('')||'<p>No reviews yet.</p>'}<details><summary>Audit history</summary>${audit.map(x=>`<p>${date(x.created_at)} · ${esc(x.actor)} · ${esc(x.action)}</p>`).join('')}</details></section>`,csrf,notice);}
export function settings(csrf:string,paused:boolean,status:any,demo:boolean){return layout('Settings',`<header><span class="eyebrow">OPERATING CONTROLS</span><h1>Clear boundaries.</h1><p>Only internal research and review are enabled in this release.</p></header><section class="card"><h2>Research processing</h2><form method="post" action="/pause">${token(csrf)}<input type="hidden" name="paused" value="${!paused}"><p>Current state: <strong>${paused?'Paused':'Running'}</strong>. Pausing prevents new jobs from starting; an in-flight run may finish.</p><button>${paused?'Resume research':'Pause research'}</button></form></section><section class="card"><h2>Connections</h2><table><tbody><tr><td>Claude + Tavily research</td><td>${status.research?'Credentials present; live access not verified':'Pending credentials / approved domains'}</td></tr>${['HubSpot lookup / promotion','Notion strategy / tasks','Canonical inbound intake','External messages','Owner-accepted handoffs'].map(s=>`<tr><td>${s}</td><td>Not implemented / disabled</td></tr>`).join('')}<tr><td>Invented demo research</td><td>${demo?'Enabled and labeled':'Disabled'}</td></tr></tbody></table></section><section class="card"><h2>Research configuration</h2><p>Configure approved source domains, the Claude model, API credentials, and pricing estimates in Railway. Secrets are never displayed here.</p><ul><li>APPROVED_RESEARCH_DOMAINS: comma-separated public domains.</li><li>ANTHROPIC_API_KEY, ANTHROPIC_MODEL, TAVILY_API_KEY</li><li>MODEL_INPUT_USD_PER_MILLION, MODEL_OUTPUT_USD_PER_MILLION, SEARCH_USD_PER_REQUEST, MAX_RUN_USD</li></ul><p>One search and one analysis call per attempt, at most five excerpts, a 90-second deadline, and three crash-recovery attempts. Budget estimates depend on the configured prices. Set provider-side spending limits as well.</p><h3>Qualification rubric · hypothesis v1</h3><p>Strategic fit 25% · Distribution 25% · Technical 20% · Commercial 15% · Timing 15%. Unknowns remain unknown. Rubric editing and calibration are deferred.</p></section>`,csrf);}
